/**
 * Writes docs/swahili-review.md: every interface string, English beside
 * Kiswahili, grouped by screen area, with an empty "Reviewer" column.
 *
 *   npx tsx scripts/i18n-review.ts
 *
 * The brand guidelines require Swahili terminology to be reviewed with
 * intended users before release; this is the sheet to hand them.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { catalogues } from "../src/lib/i18n/catalogues";

type Flat = Record<string, string>;

function flatten(node: unknown, prefix = "", out: Flat = {}): Flat {
  if (typeof node === "string") out[prefix] = node;
  else if (node && typeof node === "object") {
    for (const [key, value] of Object.entries(node)) flatten(value, prefix ? `${prefix}.${key}` : key, out);
  }
  return out;
}

const en = flatten(catalogues.en);
const sw = flatten(catalogues.sw);
const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");

const groups = new Map<string, string[]>();
for (const key of Object.keys(en)) {
  const group = key.split(".")[0];
  groups.set(group, [...(groups.get(group) ?? []), key]);
}

const total = Object.keys(en).length;
let out = `# Kiswahili review sheet

Generated by \`npx tsx scripts/i18n-review.ts\` — do not edit by hand; change the
catalogues in \`web/src/lib/i18n/messages/\` and regenerate.

**${total} strings.** Every Kiswahili string is a draft written for review. Please
read each line as a site engineer would meet it on a phone, and mark anything
that is unnatural, too formal, uses a term you would not use on site, or changes
the meaning. Notes on names and terms:

- \`Mhandisi Makini\` and the tagline \`Let's build together\` stay as they are (brand guidelines).
- \`{count}\`, \`{name}\`, \`{email}\` and similar are filled in by the app.
- Lines with "one / other" are the singular and plural forms.
- The glossary of agreed terms is in \`web/src/lib/i18n/README.md\`.

## Questions for the reviewers

These are the terms the translators were least sure of. Please answer them first.

1. **"Kiasi"** is used for both *Quantity* and *Amount* (money). Should *Amount* be "Kiasi cha fedha" or "Kiasi (TZS)"?
2. **Variation** is "Badiliko la kazi" (plural "Mabadiliko ya kazi"). Do site teams say this, or keep "Variation" in English?
3. **Labour** is "Vibarua". Is that right for the cost category, or would you say "Kazi ya mikono" or "Fundi"?
4. **Available Float** is "Fedha zinazopatikana" and **Commitments** is "Ahadi za malipo". Do these read as clearly as the English?
5. **Status words agree with the thing they describe** (a funding request "Limetumwa", an order "Imetumwa"). Please check each noun class is right.
6. **Stage and task states**: "Inaendelea" (in progress), "Tayari kufungwa" (ready for closeout), "Imewekwa kumbukumbu" (archived), "Inasubiri fedha" (awaiting funding).
7. **Closeout terms**: "Zuio la malipo" (retention), "Weka kwenye kumbukumbu" (archive), "Imehamishwa" and "Imefutwa" (carried forward, written off).
8. **Delivery** is "Uwasilishaji". Is there a term site engineers use for receiving materials?
9. **Payment methods**: "Pesa za simu" (mobile money), "Hundi" (cheque).
10. **Account deletion warning** (\`settings.deletion.*\`): it must be precise and unambiguous. Please read it carefully.
11. **Letterhead**: "Nembo ya kichwa cha hati" — is there a more common word?

Not translated yet: messages the server produces (validation errors from Server Actions, alert texts, issued PDFs/JPGs, e-mails) and the legal pages.
`;
for (const [group, keys] of groups) {
  out += `\n## ${group} (${keys.length})\n\n| Key | English | Kiswahili | Reviewer |\n|---|---|---|---|\n`;
  for (const key of keys) out += `| \`${key}\` | ${cell(en[key])} | ${cell(sw[key] ?? "")} | |\n`;
}
writeFileSync(resolve(__dirname, "../../docs/swahili-review.md"), out);
console.log(`Wrote docs/swahili-review.md (${total} strings, ${groups.size} areas)`);
