/**
 * Writes docs/swahili-review.md: every interface string, English beside
 * Kiswahili, grouped by screen area, with an empty "Reviewer" column.
 *
 *   npx tsx scripts/i18n-review.ts
 *
 * The brand guidelines require Swahili terminology to be reviewed with
 * intended users before release; this is the sheet to hand them.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { catalogues } from "../src/lib/i18n/catalogues";

type Flat = Record<string, string>;

function flatten(node: unknown, prefix = "", out: Flat = {}): Flat {
  if (typeof node === "string") out[prefix] = node;
  else if (node && typeof node === "object") {
    for (const [key, value] of Object.entries(node)) flatten(value, prefix ? `${prefix}.${key}` : key, out);
  }
  return out;
}

const en = flatten(catalogues.en);
const sw = flatten(catalogues.sw);
const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");

const groups = new Map<string, string[]>();
for (const key of Object.keys(en)) {
  const group = key.split(".")[0];
  groups.set(group, [...(groups.get(group) ?? []), key]);
}

const total = Object.keys(en).length;
let out = `# Kiswahili review sheet

Generated by \`npx tsx scripts/i18n-review.ts\` — do not edit by hand; change the
catalogues in \`web/src/lib/i18n/messages/\` and regenerate.

**${total} strings.** Every Kiswahili string is a draft written for review. Please
read each line as a site engineer would meet it on a phone, and mark anything
that is unnatural, too formal, uses a term you would not use on site, or changes
the meaning. Notes on names and terms:

- \`Mhandisi Makini\` and the tagline \`Let's build together\` stay as they are (brand guidelines).
- \`{count}\`, \`{name}\`, \`{email}\` and similar are filled in by the app.
- Lines with "one / other" are the singular and plural forms.
- The glossary of agreed terms is in \`web/src/lib/i18n/README.md\`.

## Reviewer decisions

The reviewer answered the terminology questions; the answers are applied in the catalogue.

| # | Question | Answer | Applied |
|---|---|---|---|
| 1 | \`Kiasi\` is used for both Quantity and Amount (money). Should Amount be "Kiasi cha fedha" or "Kiasi (TZS)"? | "Yes" (did not choose one) | **Open** — labelled money fields keep "Kiasi (TZS)" |
| 2 | Variation is "Badiliko la kazi" (plural "Mabadiliko ya kazi") | Yes, keep | Kept |
| 3 | Labour is "Vibarua"; would "Kazi ya mikono" or "Fundi" be better? | "Fundi" | Yes: the labour cost category and phrases such as "Makubaliano ya fundi" now use "Fundi". The line about crews and tradespeople still says "vibarua" because it means the people |
| 4 | Available Float "Fedha zinazopatikana", Commitments "Ahadi za malipo" | Yes, clear | Kept |
| 5 | Status words agree with the noun (funding request "Limetumwa", order "Imetumwa") | "Imetumwa" | Yes: funding request statuses now use the "Imetumwa / Imeghairiwa / Imefungwa" forms. Variations keep "Li-" forms (Badiliko is class 5) |
| 6 | Stage and task states ("Inaendelea", "Tayari kufungwa", "Imewekwa kumbukumbu", "Inasubiri fedha") | Yes | Kept |
| 7 | Closeout terms ("Zuio la malipo", "Weka kwenye kumbukumbu", "Imehamishwa", "Imefutwa") | Yes | Kept |
| 8 | Delivery is "Uwasilishaji" | No answer yet | Kept |
| 9 | Payment methods "Pesa za simu", "Hundi" | No answer yet | Kept |
| 10 | Account deletion warning (\`settings.deletion.*\`) | No answer yet | Kept; still needs a careful read |
| 11 | Letterhead: "Nembo ya kichwa cha hati" — a more common word? | "Nembo ya kichwa cha barua" | Yes |

Also applied from the reviewer's edits in the sheet: "Umesahau nywila yako?" and "Kiambatanisho" (Attachment). Password is "Nywila" throughout, as instructed; the sheet the reviewer edited had "Nenosiri" in seven rows, which was treated as a leftover, not a decision.

Not translated yet: messages the server produces (validation errors from Server Actions, alert texts, issued PDFs/JPGs, e-mails) and the legal pages.
`;
for (const [group, keys] of groups) {
  out += `\n## ${group} (${keys.length})\n\n| Key | English | Kiswahili | Reviewer |\n|---|---|---|---|\n`;
  for (const key of keys) out += `| \`${key}\` | ${cell(en[key])} | ${cell(sw[key] ?? "")} | |\n`;
}
writeFileSync(resolve(__dirname, "../../docs/swahili-review.md"), out);
console.log(`Wrote docs/swahili-review.md (${total} strings, ${groups.size} areas)`);
